import { brand, palette } from './colors';

export type ThemeMode = 'light' | 'dark';
export type ThemePreference = 'system' | ThemeMode;

const common = {
  primary: brand.primary,
  primaryPressed: palette.blue600,
  primarySoft: palette.blue50,
  secondary: brand.secondary,
  secondaryPressed: palette.teal500,
  secondarySoft: palette.teal50,
  success: palette.green500,
  successSoft: palette.green50,
  warning: palette.amber500,
  warningSoft: palette.amber50,
  error: palette.red500,
  errorSoft: palette.red50,
  info: palette.sky500,
  infoSoft: palette.sky50,
  textInverse: palette.white,
  link: brand.primary,
  focus: brand.secondary,
} as const;

export const themes = {
  light: {
    ...common,
    background: palette.slate50,
    surface: palette.white,
    surfaceElevated: palette.white,
    surfaceMuted: palette.slate100,
    text: palette.slate900,
    textMuted: palette.slate600,
    textSubtle: palette.slate500,
    border: palette.slate200,
    borderStrong: palette.slate300,
    divider: palette.slate200,
    overlay: 'rgba(7, 17, 31, 0.54)',
    scrim: 'rgba(7, 17, 31, 0.72)',
    inputBackground: palette.white,
    inputBorder: palette.slate300,
    cardBackground: palette.white,
    headerBackground: palette.white,
    tabBarBackground: palette.white,
    disabled: palette.slate200,
    placeholder: palette.slate500,
  },
  dark: {
    ...common,
    primarySoft: '#132B50',
    secondarySoft: '#10383C',
    successSoft: '#133524',
    warningSoft: '#3D2E0B',
    errorSoft: '#421D22',
    infoSoft: '#123244',
    background: '#080E18',
    surface: '#111A28',
    surfaceElevated: '#182334',
    surfaceMuted: '#202C3D',
    text: '#F4F7FB',
    textMuted: '#B5C0CE',
    textSubtle: '#8E9BAD',
    border: '#2A3749',
    borderStrong: '#405068',
    divider: '#283649',
    overlay: 'rgba(0, 0, 0, 0.60)',
    scrim: 'rgba(0, 0, 0, 0.78)',
    inputBackground: '#111A28',
    inputBorder: '#405068',
    cardBackground: '#111A28',
    headerBackground: '#111A28',
    tabBarBackground: '#111A28',
    disabled: '#354256',
    placeholder: '#8E9BAD',
  },
} as const;

export type ThemeTokens = (typeof themes)[ThemeMode];
